### ISSUE TITLE
option to hide sidebar switch

### ISSUE THREAD

**Issue by atomGit** [Infocatcher/Sidebars_List#15]
i have the switch set to 1px, but ideally i'd like to set it to 0 and still be able to click it - i don't know if this could best be done by making it transparent (CSS?), or detecting the cursor when it's on the screen edge

**Comment by Infocatcher** [comment]
You can use following <a href="http://kb.mozillazine.org/UserChrome.css">userChrome.css</a> trick to hide switcher:
```css
#sidebarsList-splitter {
	opacity: 0;
	min-width: 8px !important;
	margin-right: -8px !important; /* Should be the same as "min-width" */
}
```
